# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Modeling Surface and Ecological Systems
email: your-email@domain.com
description: Research and thoughts on modeling Earth's surface and ecological system. Provided by Konrad Hafen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kchafen
github_username:  khafen74
author: Konrad Hafen

# Build settings
markdown: kramdown

collections:
    pubs:
    projects:
        output: true
    tutorials:
        output: true
    present:
        output: true