# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Modeling Surface and Ecological Systems
email: your-email@domain.com
description: The research website of Konrad Hafen, a graduate student at Utah State University. Content is aimed at providing thoughts, methods, reserach, and tutorials related to modeling Earth's surface and ecological systems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kchafen
github_username:  khafen74
author: Konrad Hafen

# Build settings
markdown: kramdown

collections:
    pubs:
    present:
        output: true
    poster:
        output: true
    projects:
        output: true
    tutorials:
        output: true